import type {
  ActivityEvent,
  ActivitySummary,
  SecuritySignal,
  ActivityAction,
  RiskLevel,
  ActivitySource,
} from './types';

// ============================================================
// Helpers
// ============================================================

export const getActionColor = (action: ActivityAction): string => {
  const colors: Record<string, string> = {
    login: '#10B981',
    logout: '#6B7280',
    password_change: '#F59E0B',
    two_factor_change: '#8B5CF6',
    profile_update: '#3B82F6',
    approval: '#10B981',
    rejection: '#EF4444',
    override: '#F59E0B',
    escalation: '#EF4444',
    sensitive_view: '#8B5CF6',
    setting_change: '#6366F1',
    session_terminated: '#F59E0B',
    failed_login: '#EF4444',
    user_action: '#3B82F6',
    agent_action: '#0EA5E9',
    finance_action: '#10B981',
    zone_action: '#F97316',
    pricing_action: '#EC4899',
  };
  return colors[action] || '#6B7280';
};

export const getActionLabel = (action: ActivityAction): string => {
  const labels: Record<string, string> = {
    login: 'Login',
    logout: 'Logout',
    password_change: 'Password Change',
    two_factor_change: '2FA Change',
    profile_update: 'Profile Update',
    approval: 'Approval',
    rejection: 'Rejection',
    override: 'Override',
    escalation: 'Escalation',
    sensitive_view: 'Sensitive View',
    setting_change: 'Setting Change',
    session_terminated: 'Session Terminated',
    failed_login: 'Failed Login',
    user_action: 'User Action',
    agent_action: 'Agent Action',
    finance_action: 'Finance Action',
    zone_action: 'Zone Action',
    pricing_action: 'Pricing Action',
  };
  return labels[action] || action;
};

export const getRiskColor = (risk: RiskLevel): string => {
  const colors: Record<RiskLevel, string> = {
    low: '#10B981',
    medium: '#F59E0B',
    high: '#F97316',
    critical: '#EF4444',
  };
  return colors[risk];
};

export const getRiskLabel = (risk: RiskLevel): string => {
  const labels: Record<RiskLevel, string> = {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
  };
  return labels[risk];
};

export const getSourceLabel = (source: ActivitySource): string => {
  const labels: Record<ActivitySource, string> = {
    web: 'Web',
    api: 'API',
    mobile: 'Mobile',
    system: 'System',
  };
  return labels[source];
};

export const getOutcomeColor = (outcome: string): string => {
  const colors: Record<string, string> = {
    success: '#10B981',
    failed: '#EF4444',
    pending: '#F59E0B',
  };
  return colors[outcome] || '#6B7280';
};

export const getSignalColor = (severity: string): string => {
  return severity === 'critical' ? '#EF4444' : '#F59E0B';
};

// ============================================================
// Activity Summary
// ============================================================

export const mockActivitySummary: ActivitySummary = {
  recentLogins: 18,
  actionsPerformed: 142,
  sensitiveActions: 9,
  distinctLocations: 3,
  lastActivityTime: '2024-01-15T09:32:00Z',
};

// ============================================================
// Activity Events
// ============================================================

export const mockActivityEvents: ActivityEvent[] = [
  // Jan 15
  {
    id: 'EVT-001',
    timestamp: '2024-01-15T09:32:00Z',
    action: 'login',
    actionLabel: 'Login',
    description: 'Logged in from Chrome on MacBook Pro',
    entityType: 'Session',
    entityId: 'SES-001',
    entityName: 'Web Session',
    outcome: 'success',
    riskLevel: 'low',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
  },
  {
    id: 'EVT-002',
    timestamp: '2024-01-15T09:45:00Z',
    action: 'approval',
    actionLabel: 'Pickup Approval',
    description: 'Approved bulk pickup reassignment for Lekki zone (12 pickups)',
    entityType: 'Pickup',
    entityId: 'PKP-BATCH-042',
    entityName: 'Lekki Bulk Reassignment',
    outcome: 'success',
    riskLevel: 'medium',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    reason: 'Agent Emeka unavailable — reassigned to Agent Chidi',
    auditRef: 'AUD-2024-01-15-001',
  },
  {
    id: 'EVT-003',
    timestamp: '2024-01-15T10:15:00Z',
    action: 'zone_action',
    actionLabel: 'Zone Boundary Edit',
    description: 'Modified boundary for Victoria Island zone — expanded coverage by 1.2 km²',
    entityType: 'Zone',
    entityId: 'ZN-003',
    entityName: 'Victoria Island',
    outcome: 'success',
    riskLevel: 'high',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    beforeState: 'Coverage: 8.4 km²',
    afterState: 'Coverage: 9.6 km²',
    reason: 'Expanding to cover new enterprise client area',
    auditRef: 'AUD-2024-01-15-002',
  },
  {
    id: 'EVT-004',
    timestamp: '2024-01-15T11:00:00Z',
    action: 'pricing_action',
    actionLabel: 'Pricing Rule Created',
    description: 'Created new pricing rule: Plastic Premium — Lagos Island',
    entityType: 'Pricing Rule',
    entityId: 'PR-018',
    entityName: 'Plastic Premium — Lagos Island',
    outcome: 'success',
    riskLevel: 'high',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    auditRef: 'AUD-2024-01-15-003',
  },
  // Jan 14
  {
    id: 'EVT-005',
    timestamp: '2024-01-14T16:45:00Z',
    action: 'sensitive_view',
    actionLabel: 'Sensitive View',
    description: 'Viewed financial summary — Outgoing Payments (₦12.4M pending)',
    entityType: 'Finance',
    entityId: 'FIN-RPT-JAN',
    entityName: 'January Payment Summary',
    outcome: 'success',
    riskLevel: 'medium',
    source: 'web',
    ipAddress: '41.58.12.77',
    device: 'Windows Desktop — Edge 120',
    location: 'Abuja, Nigeria',
  },
  {
    id: 'EVT-006',
    timestamp: '2024-01-14T15:30:00Z',
    action: 'agent_action',
    actionLabel: 'Agent Deactivation',
    description: 'Deactivated agent Tunde Bakare (AGT-089) — compliance violation',
    entityType: 'Agent',
    entityId: 'AGT-089',
    entityName: 'Tunde Bakare',
    outcome: 'success',
    riskLevel: 'high',
    source: 'web',
    ipAddress: '41.58.12.77',
    device: 'Windows Desktop — Edge 120',
    location: 'Abuja, Nigeria',
    beforeState: 'Status: Active',
    afterState: 'Status: Deactivated',
    reason: 'Repeated SLA violations — 3 missed pickups in 7 days',
    auditRef: 'AUD-2024-01-14-001',
  },
  {
    id: 'EVT-007',
    timestamp: '2024-01-14T14:20:00Z',
    action: 'finance_action',
    actionLabel: 'Payment Approval',
    description: 'Approved outgoing payment batch — ₦2,450,000 to 34 agents',
    entityType: 'Payment',
    entityId: 'PAY-BATCH-015',
    entityName: 'Agent Payout Batch #15',
    outcome: 'success',
    riskLevel: 'critical',
    source: 'web',
    ipAddress: '41.58.12.77',
    device: 'Windows Desktop — Edge 120',
    location: 'Abuja, Nigeria',
    auditRef: 'AUD-2024-01-14-002',
  },
  {
    id: 'EVT-008',
    timestamp: '2024-01-14T09:00:00Z',
    action: 'login',
    actionLabel: 'Login',
    description: 'Logged in from Edge on Windows Desktop',
    entityType: 'Session',
    entityId: 'SES-003',
    entityName: 'Web Session',
    outcome: 'success',
    riskLevel: 'low',
    source: 'web',
    ipAddress: '41.58.12.77',
    device: 'Windows Desktop — Edge 120',
    location: 'Abuja, Nigeria',
  },
  // Jan 13
  {
    id: 'EVT-009',
    timestamp: '2024-01-13T11:00:00Z',
    action: 'profile_update',
    actionLabel: 'Profile Update',
    description: 'Updated phone number from +234 801 234 0000 to +234 801 234 5678',
    entityType: 'Profile',
    entityId: 'ADM-001',
    entityName: 'Adaeze Nwosu',
    outcome: 'success',
    riskLevel: 'low',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    beforeState: 'Phone: +234 801 234 0000',
    afterState: 'Phone: +234 801 234 5678',
  },
  {
    id: 'EVT-010',
    timestamp: '2024-01-13T10:30:00Z',
    action: 'user_action',
    actionLabel: 'User Suspension',
    description: 'Suspended recycler Bola Adeyemi (USR-1042) — fraudulent weight claims',
    entityType: 'User',
    entityId: 'USR-1042',
    entityName: 'Bola Adeyemi',
    outcome: 'success',
    riskLevel: 'high',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    beforeState: 'Status: Active',
    afterState: 'Status: Suspended',
    reason: 'Fraudulent weight claims detected — 3 incidents in 2 weeks',
    auditRef: 'AUD-2024-01-13-001',
  },
  // Jan 10
  {
    id: 'EVT-011',
    timestamp: '2024-01-10T09:00:00Z',
    action: 'password_change',
    actionLabel: 'Password Change',
    description: 'Password changed successfully',
    entityType: 'Security',
    entityId: 'ADM-001',
    entityName: 'Adaeze Nwosu',
    outcome: 'success',
    riskLevel: 'medium',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    auditRef: 'AUD-2024-01-10-001',
  },
  // Jan 8
  {
    id: 'EVT-012',
    timestamp: '2024-01-08T22:15:00Z',
    action: 'failed_login',
    actionLabel: 'Failed Login',
    description: 'Failed login attempt — incorrect password from unknown device',
    entityType: 'Session',
    entityId: 'SES-FAIL-001',
    entityName: 'Failed Session',
    outcome: 'failed',
    riskLevel: 'critical',
    source: 'web',
    ipAddress: '197.210.55.44',
    device: 'Unknown device — Chrome 119',
    location: 'Port Harcourt, Nigeria',
  },
  {
    id: 'EVT-013',
    timestamp: '2024-01-08T22:16:00Z',
    action: 'failed_login',
    actionLabel: 'Failed Login',
    description: 'Failed login attempt — incorrect password (2nd attempt)',
    entityType: 'Session',
    entityId: 'SES-FAIL-002',
    entityName: 'Failed Session',
    outcome: 'failed',
    riskLevel: 'critical',
    source: 'web',
    ipAddress: '197.210.55.44',
    device: 'Unknown device — Chrome 119',
    location: 'Port Harcourt, Nigeria',
  },
  // Jan 5
  {
    id: 'EVT-014',
    timestamp: '2024-01-05T10:30:00Z',
    action: 'two_factor_change',
    actionLabel: '2FA Enabled',
    description: 'Enabled two-factor authentication via Authenticator app',
    entityType: 'Security',
    entityId: 'ADM-001',
    entityName: 'Adaeze Nwosu',
    outcome: 'success',
    riskLevel: 'medium',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    auditRef: 'AUD-2024-01-05-001',
  },
  // Jan 3
  {
    id: 'EVT-015',
    timestamp: '2024-01-03T15:00:00Z',
    action: 'session_terminated',
    actionLabel: 'Session Terminated',
    description: 'Terminated session on Windows Desktop (Abuja) remotely',
    entityType: 'Session',
    entityId: 'SES-003',
    entityName: 'Windows Desktop Session',
    outcome: 'success',
    riskLevel: 'low',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
  },
  {
    id: 'EVT-016',
    timestamp: '2024-01-03T14:00:00Z',
    action: 'setting_change',
    actionLabel: 'Setting Change',
    description: 'Updated notification preferences — disabled Operations email alerts',
    entityType: 'Settings',
    entityId: 'NP-005',
    entityName: 'Notification Preferences',
    outcome: 'success',
    riskLevel: 'low',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    beforeState: 'Agent Status Changes: Email ON',
    afterState: 'Agent Status Changes: Email OFF',
  },
  // Jan 2
  {
    id: 'EVT-017',
    timestamp: '2024-01-02T14:00:00Z',
    action: 'agent_action',
    actionLabel: 'Agent Activation',
    description: 'Activated agent Emeka Okafor (AGT-042) — onboarding complete',
    entityType: 'Agent',
    entityId: 'AGT-042',
    entityName: 'Emeka Okafor',
    outcome: 'success',
    riskLevel: 'medium',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    beforeState: 'Status: Pending',
    afterState: 'Status: Active',
    auditRef: 'AUD-2024-01-02-001',
  },
  {
    id: 'EVT-018',
    timestamp: '2024-01-02T11:30:00Z',
    action: 'override',
    actionLabel: 'Override',
    description: 'Overrode SLA tier for Ikeja zone — upgraded from Standard to Premium',
    entityType: 'Zone',
    entityId: 'ZN-005',
    entityName: 'Ikeja',
    outcome: 'success',
    riskLevel: 'high',
    source: 'web',
    ipAddress: '105.112.45.123',
    device: 'MacBook Pro 16" — Chrome 120',
    location: 'Lagos, Nigeria',
    beforeState: 'SLA Tier: Standard',
    afterState: 'SLA Tier: Premium',
    reason: 'Enterprise client requirement — Dangote Recycling contract',
    auditRef: 'AUD-2024-01-02-002',
  },
  // Jan 1
  {
    id: 'EVT-019',
    timestamp: '2024-01-01T08:00:00Z',
    action: 'login',
    actionLabel: 'Login',
    description: 'Logged in from Safari on iPhone 15 Pro',
    entityType: 'Session',
    entityId: 'SES-002',
    entityName: 'Mobile Session',
    outcome: 'success',
    riskLevel: 'low',
    source: 'mobile',
    ipAddress: '105.112.45.189',
    device: 'iPhone 15 Pro — Safari Mobile',
    location: 'Lagos, Nigeria',
  },
  {
    id: 'EVT-020',
    timestamp: '2024-01-01T08:05:00Z',
    action: 'sensitive_view',
    actionLabel: 'Sensitive View',
    description: 'Viewed wallet float balance — ₦45.2M available',
    entityType: 'Finance',
    entityId: 'WALLET-001',
    entityName: 'Main Wallet Float',
    outcome: 'success',
    riskLevel: 'medium',
    source: 'mobile',
    ipAddress: '105.112.45.189',
    device: 'iPhone 15 Pro — Safari Mobile',
    location: 'Lagos, Nigeria',
  },
];

// ============================================================
// Security Signals
// ============================================================

export const mockSecuritySignals: SecuritySignal[] = [
  {
    id: 'SIG-001',
    type: 'failed_login',
    severity: 'critical',
    title: '2 Failed Login Attempts',
    description: 'Two consecutive failed login attempts from Port Harcourt (197.210.55.44) on Jan 8 at 10:15 PM. This IP is not in your usual login locations.',
    timestamp: '2024-01-08T22:16:00Z',
    acknowledged: false,
  },
  {
    id: 'SIG-002',
    type: 'location_anomaly',
    severity: 'warning',
    title: 'New Login Location Detected',
    description: 'First login from Abuja, Nigeria on Jan 14. Your usual locations are Lagos only. If this was you, no action needed.',
    timestamp: '2024-01-14T09:00:00Z',
    acknowledged: true,
  },
  {
    id: 'SIG-003',
    type: 'unusual_time',
    severity: 'warning',
    title: 'Late Night Activity',
    description: 'Login activity detected at 10:15 PM on Jan 8 from an unrecognized device. This is outside your typical usage hours (8 AM – 7 PM).',
    timestamp: '2024-01-08T22:15:00Z',
    acknowledged: false,
  },
  {
    id: 'SIG-004',
    type: 'new_device',
    severity: 'warning',
    title: 'New Device Detected',
    description: 'Windows Desktop with Edge 120 was used for the first time on Jan 14 from Abuja. Verify this was an authorized device.',
    timestamp: '2024-01-14T09:00:00Z',
    acknowledged: true,
  },
];

// ============================================================
// Activity Type Filter Options
// ============================================================

export const activityTypeOptions: { value: string; label: string }[] = [
  { value: '', label: 'All Activities' },
  { value: 'login', label: 'Logins' },
  { value: 'logout', label: 'Logouts' },
  { value: 'password_change', label: 'Password Changes' },
  { value: 'two_factor_change', label: '2FA Changes' },
  { value: 'profile_update', label: 'Profile Updates' },
  { value: 'approval', label: 'Approvals' },
  { value: 'rejection', label: 'Rejections' },
  { value: 'override', label: 'Overrides' },
  { value: 'escalation', label: 'Escalations' },
  { value: 'sensitive_view', label: 'Sensitive Views' },
  { value: 'setting_change', label: 'Setting Changes' },
  { value: 'session_terminated', label: 'Session Terminations' },
  { value: 'failed_login', label: 'Failed Logins' },
  { value: 'user_action', label: 'User Actions' },
  { value: 'agent_action', label: 'Agent Actions' },
  { value: 'finance_action', label: 'Finance Actions' },
  { value: 'zone_action', label: 'Zone Actions' },
  { value: 'pricing_action', label: 'Pricing Actions' },
];
